name: Auto Assign
on:
  pull_request:
    types: [opened, edited]    
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: scient122, aminesr97
          skipKeywords: wip, draft
