name: reviewdog
on:
  pull_request:
    paths:
      - '**.java'
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 
    steps:
      - uses: actions/checkout@v3
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          workdir: src/main
